[package]
name = "cryptomator"
version = "0.1.0"
authors = ["programmer10110 <programmer10110@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1"
base64 = "0.13.0"
base32 = "0.4.0"
scrypt = { version = "0.2", default-features = false }
openssl = { version = "0.10"}
aes-siv = "0.5.0"
aes-ctr = "0.6.0"
hmac = "0.10.1"
sha2 = "0.9.2"
byteorder = "1"
sha1 = "0.6.0"
rand = "0.7.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
rsfs = { git = "https://github.com/programmer10110/rsfs" }
webdav-handler = { git = "https://github.com/programmer10110/webdav-handler-rs", branch = "win"}
futures = "0.3.12"
http = "0.1.17"
hyper = { version = "0.14.2", features = [ "http1", "http2", "server", "stream", "runtime" ] }
tokio = { version = "1.0.2", features = ["full"] }
bytes = "1.0.1"
log = "0.4.14"
slog = "2.5.2"
slog-stdlog = "4.1.0"
slog-term = "2.4.0"
slog-envlogger = "2.2.0"
slog-async = "2.6.0"
slog-scope = "4.4.0"
lru = "0.6.5"
time = { version = "0.2.24", features = ["std"] }


[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
panic = "unwind"