[package]
name = "cryptomator"
version = "0.1.0"
authors = ["programmer10110 <programmer10110@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1"
base64 = "0.13.0"
base32 = "0.4.0"
scrypt = { version = "0.2", default-features = false }
openssl = { version = "0.10", features = ["vendored"] }
aes-siv = "0.5.0"